### ISSUE TITLE
eLife: meta issue

### ISSUE THREAD

**Issue by nokome** [stencila/encoda#398]
This is a "meta" issue to organise and prioritise issues related to eLife's integration of Encoda. Grouped by the `<codec>.<decode|encode>` (for most codecs only one method is needed for the envisioned workflow).

#### `elife.decode`

The latest version of the eLife article is fetched as JATS XML and images for each figure downloaded from their image server. Currently working OK, but some fixes and refactoring to do:

- [x] #368
- [ ] #379 (straight forward but low priority - just refactoring that does not fix a bug or add a feature)

#### `jats.decode`

The `elife` codec delegates to the `jats` codec. Currently, decoding the contents (i.e. `<body>`) of the article OK, but needs work to extract `<front>` and `<back>` to capture original article as completely and accurately as possible:

- [x] `<front>`: #395  being addressed in #396 
- [ ] `<back>`: #421 is a PR addressing several issues
- [ ] `<body>`

#### `jsonld.encode`

JSON-LD will be used as the canonical format for an article in a snapshot zip file. The zip needs to include assets e.g. images and data:

- [x] #388
- [x] #386

#### `html.encode`

The `html` codec will be used to generate HTML from JSON-LD.

- [x] #397
- [x] #399
- [x] #381
- [x] #386

Other issues, related to codecs more involved in authoring, will be added here too.

**Comment by nokome** [comment]
@all-contributors please add @FAtherden-eLife  for bug reporting and planning.

**Comment by nokome** [comment]
Closing this as, IMO, it no longer has much value as a meta-issue. Will instead be planning these issues via the kanban board.
